<?php
    $name=(isset($_POST["nombre"])&&$_POST["nombre"]!="")?$_POST["nombre"]:"Inválido";
    $apellP=(isset($_POST["aPaterno"])&&$_POST["aPaterno"]!="")?$_POST["aPaterno"]:"Inválido";
    $apellM=(isset($_POST["aMaterno"])&&$_POST["aMaterno"]!="")?$_POST["aMaterno"]:"Inválido";
    $gender=(isset($_POST["gender"])&&$_POST["gender"]!="")?$_POST["gender"]:"Inválido";
    $age=(isset($_POST["age"])&&$_POST["age"]!="")?$_POST["age"]:"Inválido";
    $email=(isset($_POST["mail"])&&$_POST["mail"]!="")?$_POST["mail"]:"Inválido";
    $phone=(isset($_POST["phone"])&&$_POST["phone"]!="")?$_POST["phone"]:"Inválido";
    $cell=(isset($_POST["cell"])&&$_POST["cell"]!="")?$_POST["cell"]:"Inválido";
    $school=(isset($_POST["from"])&&$_POST["from"]!="")?$_POST["from"]:"Inválido";
    $prom=(isset($_POST["promedio"])&&$_POST["promedio"]!="")?$_POST["promedio"]:"Inválido";
    $first=(isset($_POST["first"])&&$_POST["first"]!="")?$_POST["first"]:"Inválido";
    $second=(isset($_POST["second"])&&$_POST["second"]!="")?$_POST["second"]:"Inválido";

    //  echo $name;
    //  echo $apellP;
    //  echo $apellM;
    //  echo $gender;
    //  echo $age;
    //  echo $email;
    //  echo $phone;
    //  echo $cell;
    //  echo $school;
    //  echo $prom;
    //  echo $first;
    // echo $second;

    echo "<table border="."1"." width="."900".">";
        echo"<thead>";
            echo"<th colspan="."4"."><h2>Solicitud de ingreso a la Universidad<h2></th>";
        echo"</thead>";
        echo"<tbody>";
            echo "<tr>";
                echo"<td>".$apellP."</td>";
                echo"<td>".$apellM."</td>";
                echo"<td colspan="."2".">".$name."</td>";
            echo"</tr>";
            echo "<tr>";
                echo"<td><strong><u>Apellido paterno</u></strong></td>";
                echo"<td><strong><u>Apellido materno</u></strong></td>";
                echo"<td colspan="."2"."><strong><u>Nombre(s)</u></strong></td>";
            echo"</tr>";
            echo "<tr>";
                echo"<td><strong><u>Género:</u></strong></td>";
                echo"<td>".$gender."</td>";
                echo"<td><strong><u>Edad:</u></strong></td>";
                echo"<td>".$age."</td>";
            echo"</tr>";        
            echo "<tr>";
                echo "<td colspan="."2".">".$email."</td>";
                echo "<td>".$phone."</td>";
                echo "<td>".$cell."</td>";
            echo "</tr>";
            echo "<tr>";
                echo"<td colspan="."2"."><strong><u>Correo electrónico</u></strong></td>";
                echo"<td><strong><u>Teléfono</u></strong></td>";
                echo"<td><strong><u>Celular</u></strong></td>";
            echo "</tr>";
            echo "<tr>";
                echo"<td><strong><u>Escuela de procedencia:</u></strong></td>";
                echo "<td>".$school."</td>";
                echo"<td><strong><u>Promedio:</u></strong></td>";
                echo "<td>".$prom."</td>";    
            echo "</tr>";
            echo "<tr>";
            echo"<td colspan="."2"."><strong><u>Primera opción</u></strong></td>";
                echo "<td colspan="."2".">".$first."</td>";
            echo "</tr>";
            echo "<tr>";
            echo"<td colspan="."2"."><strong><u>Segunda opción</u></strong></td>";
                echo "<td colspan="."2".">".$second."</td>";
            echo "</tr>";
        echo"</tbody>";
    echo "</table>";
?>